<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attribute' => 'Atributo',
    'Data' => 'Dados',
    'Foreign PK' => 'Chave',
    'From' => 'De',
    'Happened at' => 'Data',
    'Table name' => 'Nome da Tabela',
    'To' => 'Para',
    'Type' => 'Evento',
    'User ID' => 'Usuário',
    'Birthday of {customer}' => 'Aniversário de {customer}',
    'Congratulations!' => 'Parabéns!',
    'Delete' => 'Remover',
    'No disk space left' => 'Sem espaço em disco',
    'Update' => 'Atualizar',
    'You got a new message' => 'Você tem uma nova mensagem',
];
