<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create' => 'Criar',
    'Address' => 'Endereço',
    'Agency' => 'Orgão',
    'Birthday' => 'Data de Nascimento',
    'City' => 'Cidade',
    'Complement' => 'Complemento',
    'Create Customer' => 'Cadastrar Cliente',
    'Customer Password' => 'Senha do Cliente',
    'Customers' => 'Clientes',
    'Document' => 'CPF/CNPJ',
    'File' => 'Arquivo',
    'Folder' => 'Diretório',
    'ID' => 'Id',
    'Mail' => 'E-mail',
    'Name' => 'Nome',
    'Neighbourhood' => 'Bairro',
    'Observation' => 'Observação',
    'Phone1' => 'Telefone 1',
    'Phone2' => 'Telefone 2',
    'Phone3' => 'Telefone 3',
    'Registry' => 'Matrícula',
    'State' => 'Estado',
    'Telemarketing' => 'Telemarketing',
    'Update' => 'Atualizar',
    'Update Customer {customer}' => 'Atualizar dados de {customer}',
    'Zip Code' => 'CEP',
];
